package grammar

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sonquer/opendba/src/tools/internal/exec"
)

func TestTransformRewritesReceivers(t *testing.T) {
	cases := []struct {
		name    string
		content string
		lexer   bool
		want    string
	}{
		{"lexer action", "{this.PushTag();}\n", true, "{l.PushTag();}\n"},
		{"lexer predicate", "{this.CheckLaMinus()}?\n", true, "{p.CheckLaMinus()}?\n"},
		{"parser action", "{this.Something();}\n", false, "{p.Something();}\n"},
		{"untouched", "SELECT: 'select';\n", true, "SELECT: 'select';\n"},
		{"repeated on one line", "{this.A(); this.B();}\n", true, "{l.A(); l.B();}\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := Transform(c.content, c.lexer); got != c.want {
				t.Errorf("Transform() = %q, want %q", got, c.want)
			}
		})
	}
}

func TestTransformPreservesFinalLineWithoutNewline(t *testing.T) {
	if got := Transform("{this.X()}", true); got != "{l.X()}" {
		t.Errorf("Transform() = %q", got)
	}
}

func TestNeedsTransform(t *testing.T) {
	if !NeedsTransform("{this.X();}") || NeedsTransform("plain") {
		t.Error("NeedsTransform must detect java style receivers")
	}
}

func TestRewritePackage(t *testing.T) {
	got := RewritePackage("package parser\n\nimport \"x\"\n", "postgresql")
	if !strings.HasPrefix(got, "package postgresql\n") {
		t.Errorf("RewritePackage() = %q", got)
	}
	if got := RewritePackage("import \"x\"\n", "postgresql"); strings.Contains(got, "package") {
		t.Errorf("RewritePackage must leave files without a package clause alone: %q", got)
	}
}

func TestSpecsCoverBothDialects(t *testing.T) {
	specs := Specs(filepath.Join("root", "src", "cli"))
	if len(specs) != 2 {
		t.Fatalf("specs = %+v", specs)
	}
	if specs[0].Dialect != "postgresql" || specs[1].Dialect != "sqlite" {
		t.Errorf("unexpected dialects: %+v", specs)
	}
	if !strings.HasSuffix(specs[0].Dir, filepath.Join("internal", "parser", "generated", "postgresql")) {
		t.Errorf("postgresql directory = %q", specs[0].Dir)
	}
	if len(specs[1].Bases) != 0 {
		t.Errorf("sqlite grammar needs no base classes, got %v", specs[1].Bases)
	}
}

type recordingRunner struct {
	calls  []string
	dirs   []string
	result exec.Result
	err    error
	emit   map[string]string
}

func (r *recordingRunner) Run(_ context.Context, dir string, name string, args ...string) (exec.Result, error) {
	r.calls = append(r.calls, exec.Format(name, args...))
	r.dirs = append(r.dirs, dir)
	for file, content := range r.emit {
		if err := os.WriteFile(filepath.Join(dir, file), []byte(content), 0o600); err != nil {
			return exec.Result{}, err
		}
	}
	return r.result, r.err
}

func newSpec(t *testing.T) Spec {
	t.Helper()
	dir := t.TempDir()
	write(t, filepath.Join(dir, "XLexer.g4"), "lexer grammar X;\nA: {this.Push();};\n")
	write(t, filepath.Join(dir, "XParser.g4"), "parser grammar X;\nroot: {this.Check()}? A;\n")
	write(t, filepath.Join(dir, "x_lexer_base.go"), "package parser\n\nfunc Base() {}\n")
	write(t, filepath.Join(dir, "stale_parser.go"), "// Code generated by ANTLR. DO NOT EDIT.\npackage x\n")
	write(t, filepath.Join(dir, "keep.go"), "package x\n\nfunc Keep() {}\n")
	return Spec{
		Dialect: "x",
		Package: "xdialect",
		Dir:     dir,
		Lexer:   "XLexer.g4",
		Parser:  "XParser.g4",
		Bases:   []string{"x_lexer_base.go"},
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

func TestGenerateInstallsOutput(t *testing.T) {
	spec := newSpec(t)
	runner := &recordingRunner{emit: map[string]string{
		"x_parser.go":   "// Code generated by ANTLR\npackage xdialect\n",
		"x_lexer.go":    "// Code generated by ANTLR\npackage xdialect\n",
		"XLexer.interp": "ignored",
	}}
	generator := Generator{Runner: runner, Jar: "/cache/antlr.jar"}

	written, err := generator.Generate(context.Background(), spec)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(written) != 2 {
		t.Fatalf("written = %v", written)
	}
	if _, err := os.Stat(filepath.Join(spec.Dir, "x_parser.go")); err != nil {
		t.Errorf("generated parser missing: %v", err)
	}
	if _, err := os.Stat(filepath.Join(spec.Dir, "stale_parser.go")); err == nil {
		t.Error("stale generated file must be removed")
	}
	if _, err := os.Stat(filepath.Join(spec.Dir, "keep.go")); err != nil {
		t.Error("hand written files must be kept")
	}
	if got := read(t, filepath.Join(spec.Dir, "x_lexer_base.go")); !strings.HasPrefix(got, "package xdialect") {
		t.Errorf("base package not rewritten: %q", got)
	}
	if _, err := os.Stat(filepath.Join(spec.Dir, "XLexer.interp")); err == nil {
		t.Error("interp files must not be installed")
	}

	command := runner.calls[0]
	for _, want := range []string{"java", "-jar /cache/antlr.jar", "-Dlanguage=Go", "-package xdialect", "-listener", "-no-visitor", "XLexer.g4", "XParser.g4"} {
		if !strings.Contains(command, want) {
			t.Errorf("command %q missing %q", command, want)
		}
	}
	if runner.dirs[0] == spec.Dir {
		t.Error("antlr must run in a staging directory, not in the vendored grammar directory")
	}
	if got := read(t, filepath.Join(spec.Dir, "XLexer.g4")); !strings.Contains(got, "this.") {
		t.Error("the vendored grammar must stay identical to upstream")
	}
}

func TestGenerateUsesConfiguredJava(t *testing.T) {
	spec := newSpec(t)
	runner := &recordingRunner{}
	generator := Generator{Runner: runner, Jar: "j.jar", Java: "/opt/java/bin/java"}
	if _, err := generator.Generate(context.Background(), spec); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !strings.HasPrefix(runner.calls[0], "/opt/java/bin/java ") {
		t.Errorf("command = %q", runner.calls[0])
	}
}

func TestGenerateFailures(t *testing.T) {
	t.Run("missing grammar", func(t *testing.T) {
		spec := newSpec(t)
		if err := os.Remove(filepath.Join(spec.Dir, "XLexer.g4")); err != nil {
			t.Fatal(err)
		}
		generator := Generator{Runner: &recordingRunner{}}
		if _, err := generator.Generate(context.Background(), spec); err == nil {
			t.Fatal("want error")
		}
	})
	t.Run("runner error", func(t *testing.T) {
		spec := newSpec(t)
		runner := &recordingRunner{err: errors.New("java missing")}
		generator := Generator{Runner: runner}
		if _, err := generator.Generate(context.Background(), spec); err == nil {
			t.Fatal("want error")
		}
	})
	t.Run("antlr reports failure", func(t *testing.T) {
		spec := newSpec(t)
		runner := &recordingRunner{result: exec.Result{ExitCode: 1, Stderr: "syntax error"}}
		generator := Generator{Runner: runner}
		_, err := generator.Generate(context.Background(), spec)
		if err == nil || !strings.Contains(err.Error(), "syntax error") {
			t.Fatalf("err = %v", err)
		}
	})
	t.Run("output directory removed", func(t *testing.T) {
		spec := newSpec(t)
		if err := os.RemoveAll(spec.Dir); err != nil {
			t.Fatal(err)
		}
		generator := Generator{Runner: &recordingRunner{}}
		if _, err := generator.Generate(context.Background(), spec); err == nil {
			t.Fatal("want error")
		}
	})
}

func TestJarNaming(t *testing.T) {
	if JarName(DefaultVersion) != "antlr-4.13.2-complete.jar" {
		t.Errorf("JarName() = %q", JarName(DefaultVersion))
	}
	if !strings.HasSuffix(JarURL("4.13.2"), "/antlr-4.13.2-complete.jar") {
		t.Errorf("JarURL() = %q", JarURL("4.13.2"))
	}
	if got := CacheDir("/home/db"); got != filepath.Join("/home/db", ".cache", "opendba-dev") {
		t.Errorf("CacheDir() = %q", got)
	}
}

func TestJarFetcherDownloadsOnce(t *testing.T) {
	hits := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		hits++
		w.Write([]byte("jar bytes"))
	}))
	defer server.Close()

	path := filepath.Join(t.TempDir(), "cache", "antlr.jar")
	fetcher := JarFetcher{Client: server.Client(), URL: server.URL}
	if err := fetcher.Ensure(context.Background(), path); err != nil {
		t.Fatalf("Ensure: %v", err)
	}
	if got := read(t, path); got != "jar bytes" {
		t.Errorf("jar content = %q", got)
	}
	if err := fetcher.Ensure(context.Background(), path); err != nil {
		t.Fatalf("second Ensure: %v", err)
	}
	if hits != 1 {
		t.Errorf("downloaded %d times, want 1", hits)
	}
}

func TestJarFetcherFailures(t *testing.T) {
	t.Run("bad status", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.WriteHeader(http.StatusNotFound)
		}))
		defer server.Close()
		fetcher := JarFetcher{Client: server.Client(), URL: server.URL}
		if err := fetcher.Ensure(context.Background(), filepath.Join(t.TempDir(), "antlr.jar")); err == nil {
			t.Fatal("want error")
		}
	})
	t.Run("unreachable", func(t *testing.T) {
		fetcher := JarFetcher{URL: "http://127.0.0.1:1/antlr.jar"}
		if err := fetcher.Ensure(context.Background(), filepath.Join(t.TempDir(), "antlr.jar")); err == nil {
			t.Fatal("want error")
		}
	})
	t.Run("invalid url", func(t *testing.T) {
		fetcher := JarFetcher{URL: "://nope"}
		if err := fetcher.Ensure(context.Background(), filepath.Join(t.TempDir(), "antlr.jar")); err == nil {
			t.Fatal("want error")
		}
	})
	t.Run("unwritable cache", func(t *testing.T) {
		blocked := filepath.Join(t.TempDir(), "file")
		write(t, blocked, "x")
		fetcher := JarFetcher{URL: "http://example.invalid"}
		if err := fetcher.Ensure(context.Background(), filepath.Join(blocked, "sub", "antlr.jar")); err == nil {
			t.Fatal("want error")
		}
	})
}

func newWorkspace(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	write(t, filepath.Join(root, "go.work"), "go 1.27.0\n\nuse ./src/cli\n")
	write(t, filepath.Join(root, "src", "cli", "go.mod"), "module example.com/m/src/cli\n\ngo 1.27.0\n")
	for _, spec := range Specs(filepath.Join(root, "src", "cli")) {
		if err := os.MkdirAll(spec.Dir, 0o755); err != nil {
			t.Fatal(err)
		}
		write(t, filepath.Join(spec.Dir, spec.Lexer), "lexer grammar X;\n")
		write(t, filepath.Join(spec.Dir, spec.Parser), "parser grammar X;\n")
		for _, base := range spec.Bases {
			write(t, filepath.Join(spec.Dir, base), "package parser\n")
		}
	}
	return root
}

func newApp(t *testing.T, root string, runner exec.Runner) (App, *bytes.Buffer, *bytes.Buffer) {
	t.Helper()
	stdout, stderr := &bytes.Buffer{}, &bytes.Buffer{}
	app := App{
		Dir:     root,
		Runner:  runner,
		Stdout:  stdout,
		Stderr:  stderr,
		Home:    t.TempDir(),
		Fetcher: func(string) JarFetcher { return JarFetcher{Client: stubClient("jar"), URL: "http://antlr.test/jar"} },
	}
	return app, stdout, stderr
}

func stubClient(body string) *http.Client {
	return &http.Client{Transport: roundTripper(func(*http.Request) (*http.Response, error) {
		return &http.Response{
			StatusCode: http.StatusOK,
			Body:       io.NopCloser(strings.NewReader(body)),
			Header:     http.Header{},
		}, nil
	})}
}

type roundTripper func(*http.Request) (*http.Response, error)

func (f roundTripper) RoundTrip(r *http.Request) (*http.Response, error) { return f(r) }

func TestAppGeneratesEveryDialect(t *testing.T) {
	root := newWorkspace(t)
	runner := &recordingRunner{emit: map[string]string{"x_parser.go": "// Code generated\npackage x\n"}}
	app, stdout, _ := newApp(t, root, runner)

	if code := app.Run(context.Background(), nil); code != ExitOK {
		t.Fatalf("exit = %d", code)
	}
	if len(runner.calls) != 2 {
		t.Fatalf("antlr ran %d times, want 2", len(runner.calls))
	}
	out := stdout.String()
	if !strings.Contains(out, "postgresql:") || !strings.Contains(out, "sqlite:") {
		t.Errorf("output = %q", out)
	}
}

func TestAppGeneratesASingleDialect(t *testing.T) {
	root := newWorkspace(t)
	runner := &recordingRunner{}
	app, stdout, _ := newApp(t, root, runner)

	if code := app.Run(context.Background(), []string{"-dialect", "sqlite"}); code != ExitOK {
		t.Fatalf("exit = %d", code)
	}
	if len(runner.calls) != 1 {
		t.Fatalf("antlr ran %d times, want 1", len(runner.calls))
	}
	if strings.Contains(stdout.String(), "postgresql:") {
		t.Error("only the requested dialect must be generated")
	}
}

func TestAppFailures(t *testing.T) {
	t.Run("bad flag", func(t *testing.T) {
		app, _, _ := newApp(t, newWorkspace(t), &recordingRunner{})
		if code := app.Run(context.Background(), []string{"-nope"}); code != ExitUsage {
			t.Fatalf("exit = %d", code)
		}
	})
	t.Run("flag help", func(t *testing.T) {
		app, _, _ := newApp(t, newWorkspace(t), &recordingRunner{})
		if code := app.Run(context.Background(), []string{"-h"}); code != ExitOK {
			t.Fatalf("exit = %d", code)
		}
	})
	t.Run("no workspace", func(t *testing.T) {
		app, _, stderr := newApp(t, t.TempDir(), &recordingRunner{})
		if code := app.Run(context.Background(), nil); code != ExitFailure {
			t.Fatalf("exit = %d", code)
		}
		if !strings.Contains(stderr.String(), "no go.work") {
			t.Errorf("stderr = %q", stderr.String())
		}
	})
	t.Run("unknown module", func(t *testing.T) {
		app, _, stderr := newApp(t, newWorkspace(t), &recordingRunner{})
		if code := app.Run(context.Background(), []string{"-module", "nope"}); code != ExitUsage {
			t.Fatalf("exit = %d", code)
		}
		if !strings.Contains(stderr.String(), "unknown module") {
			t.Errorf("stderr = %q", stderr.String())
		}
	})
	t.Run("jar download fails", func(t *testing.T) {
		app, _, stderr := newApp(t, newWorkspace(t), &recordingRunner{})
		app.Fetcher = func(string) JarFetcher { return JarFetcher{URL: "http://127.0.0.1:1/jar"} }
		if code := app.Run(context.Background(), nil); code != ExitFailure {
			t.Fatalf("exit = %d", code)
		}
		if stderr.Len() == 0 {
			t.Error("the failure must be reported")
		}
	})
	t.Run("generation fails", func(t *testing.T) {
		app, _, stderr := newApp(t, newWorkspace(t), &recordingRunner{err: errors.New("java missing")})
		if code := app.Run(context.Background(), nil); code != ExitFailure {
			t.Fatalf("exit = %d", code)
		}
		if !strings.Contains(stderr.String(), "java missing") {
			t.Errorf("stderr = %q", stderr.String())
		}
	})
}

func TestAppFallsBackToTheRealHome(t *testing.T) {
	app := App{}
	if app.home() == "" {
		t.Error("home must never be empty")
	}
	if (App{Home: "/x"}).home() != "/x" {
		t.Error("an explicit home must win")
	}
	if (App{}).fetcher("http://x").URL != "http://x" {
		t.Error("the default fetcher must use the given url")
	}
}

func TestMainRejectsBadFlags(t *testing.T) {
	if code := Main([]string{"-nope"}); code != ExitUsage {
		t.Fatalf("Main exit = %d", code)
	}
}

func TestGenerateReportsInstallFailures(t *testing.T) {
	spec := newSpec(t)
	runner := &recordingRunner{emit: map[string]string{"blocked.go": "// Code generated\npackage x\n"}}
	if err := os.Mkdir(filepath.Join(spec.Dir, "blocked.go"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(spec.Dir, "blocked.go", "keep"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	generator := Generator{Runner: runner}
	if _, err := generator.Generate(context.Background(), spec); err == nil {
		t.Fatal("want a write error")
	}
}

func TestGenerateReportsBaseRewriteFailures(t *testing.T) {
	spec := newSpec(t)
	if err := os.Remove(filepath.Join(spec.Dir, "x_lexer_base.go")); err != nil {
		t.Fatal(err)
	}
	generator := Generator{Runner: &recordingRunner{}}
	if _, err := generator.Generate(context.Background(), spec); err == nil {
		t.Fatal("want a missing base class error")
	}
}

func TestGenerateLeavesUnmarkedFilesAlone(t *testing.T) {
	spec := newSpec(t)
	generator := Generator{Runner: &recordingRunner{}}
	if _, err := generator.Generate(context.Background(), spec); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if _, err := os.Stat(filepath.Join(spec.Dir, "keep.go")); err != nil {
		t.Errorf("hand written files must survive: %v", err)
	}
}

func TestStageGrammarReportsUnwritableStaging(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "X.g4")
	write(t, source, "grammar X;\n")
	if err := stageGrammar(source, filepath.Join(dir, "missing", "X.g4"), true); err == nil {
		t.Fatal("want a staging error")
	}
}

func TestMainWithoutAWorkspace(t *testing.T) {
	dir := t.TempDir()
	previous, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(previous) })
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	if code := Main(nil); code != ExitFailure {
		t.Fatalf("Main exit = %d, want failure", code)
	}
}
