package gate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"
)

func TestIsDirective(t *testing.T) {
	cases := map[string]bool{
		"//go:build linux":       true,
		"//go:generate stringer": true,
		"//go:embed schema.json": true,
		"//line foo.go:1":        true,
		"// +build linux":        true,
		"// a normal comment":    false,
		"/* block */":            false,
		"//gopher":               false,
	}
	for text, want := range cases {
		if got := IsDirective(text); got != want {
			t.Errorf("IsDirective(%q) = %v, want %v", text, got, want)
		}
	}
}

func TestScanFSFindsComments(t *testing.T) {
	fsys := fstest.MapFS{
		"clean.go": &fstest.MapFile{Data: []byte("package a\n\nfunc F() int { return 1 }\n")},
		"dirty.go": &fstest.MapFile{Data: []byte("package a\n\nfunc G() int {\n\t// inside\n\treturn 2 // trailing\n}\n")},
		"build.go": &fstest.MapFile{Data: []byte("//go:build linux\n\npackage a\n")},
		"note.txt": &fstest.MapFile{Data: []byte("// not go\n")},
	}
	findings, err := ScanFS(fsys)
	if err != nil {
		t.Fatalf("ScanFS: %v", err)
	}
	if len(findings) != 2 {
		t.Fatalf("got %d findings, want 2: %v", len(findings), findings)
	}
	if findings[0].File != "dirty.go" || findings[0].Line != 4 {
		t.Errorf("first finding = %v, want dirty.go:4", findings[0])
	}
	if findings[1].Line != 5 {
		t.Errorf("second finding = %v, want line 5", findings[1])
	}
	if got := findings[0].String(); got != "dirty.go:4: // inside" {
		t.Errorf("String() = %q", got)
	}
}

func TestScanFSSkipsDirs(t *testing.T) {
	fsys := fstest.MapFS{
		"vendor/x/a.go":   &fstest.MapFile{Data: []byte("package x\n\nfunc A() {\n\t// vendored\n}\n")},
		"testdata/b.go":   &fstest.MapFile{Data: []byte("package x\n\nfunc B() {\n\t// fixture\n}\n")},
		".hidden/c.go":    &fstest.MapFile{Data: []byte("package x\n\nfunc C() {\n\t// hidden\n}\n")},
		"internal/ok.go":  &fstest.MapFile{Data: []byte("package x\n\nfunc D() {}\n")},
		"internal/bad.go": &fstest.MapFile{Data: []byte("package x\n\nfunc E() {\n\t/* block */\n}\n")},
	}
	findings, err := ScanFS(fsys)
	if err != nil {
		t.Fatalf("ScanFS: %v", err)
	}
	if len(findings) != 1 || findings[0].File != "internal/bad.go" {
		t.Fatalf("got %v, want only internal/bad.go", findings)
	}
}

func TestScanFSSortsFindings(t *testing.T) {
	fsys := fstest.MapFS{
		"z.go": &fstest.MapFile{Data: []byte("package a\n\nfunc Z() {\n\t// z\n}\n")},
		"a.go": &fstest.MapFile{Data: []byte("package a\n\nfunc A() {\n\t// a\n}\n")},
	}
	findings, err := ScanFS(fsys)
	if err != nil {
		t.Fatalf("ScanFS: %v", err)
	}
	if findings[0].File != "a.go" || findings[1].File != "z.go" {
		t.Fatalf("not sorted: %v", findings)
	}
}

func TestScanFSParseError(t *testing.T) {
	fsys := fstest.MapFS{"broken.go": &fstest.MapFile{Data: []byte("package ???\n")}}
	if _, err := ScanFS(fsys); err == nil {
		t.Fatal("want parse error")
	}
}

func TestFirstLineTruncates(t *testing.T) {
	long := "// " + string(make([]byte, 0))
	for i := 0; i < 100; i++ {
		long += "x"
	}
	got := []rune(firstLine(long))
	if len(got) != 73 {
		t.Errorf("len = %d, want 73: %q", len(got), string(got))
	}
	if got := firstLine("/* one\ntwo */"); got != "/* one …" {
		t.Errorf("multiline = %q", got)
	}
}

func TestScanDirectory(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.go"), []byte("package a\n\nfunc A() {\n\t// nope\n}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	findings, err := Scan(dir)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(findings) != 1 {
		t.Fatalf("got %v", findings)
	}
}

func TestScanRejectsNonDirectory(t *testing.T) {
	file := filepath.Join(t.TempDir(), "f.go")
	if err := os.WriteFile(file, []byte("package a\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := Scan(file); err == nil {
		t.Fatal("want error for file root")
	}
	if _, err := Scan(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatal("want error for missing root")
	}
}

func TestIsGenerated(t *testing.T) {
	cases := map[string]bool{
		"// Code generated from PostgreSQLParser.g4 by ANTLR 4.13.2. DO NOT EDIT.\n\npackage x\n": true,
		"// Code generated by mockgen. DO NOT EDIT.\npackage x\n":                                 true,
		"package x\n\n// Code generated later. DO NOT EDIT.\n":                                    false,
		"// a normal comment\npackage x\n":                                                        false,
		"package x\n":                                                                             false,
		"":                                                                                        false,
	}
	for source, want := range cases {
		if got := IsGenerated([]byte(source)); got != want {
			t.Errorf("IsGenerated(%q) = %v, want %v", source, got, want)
		}
	}
}

func TestScanFSSkipsGeneratedFiles(t *testing.T) {
	fsys := fstest.MapFS{
		"generated/parser.go": &fstest.MapFile{Data: []byte("// Code generated by ANTLR. DO NOT EDIT.\n\npackage p\n\nfunc A() {\n\t// inner comment\n}\n")},
		"handwritten.go":      &fstest.MapFile{Data: []byte("package p\n\nfunc B() {\n\t// mine\n}\n")},
	}
	findings, err := ScanFS(fsys)
	if err != nil {
		t.Fatalf("ScanFS: %v", err)
	}
	if len(findings) != 1 || findings[0].File != "handwritten.go" {
		t.Fatalf("findings = %v", findings)
	}
}

func TestDocumentationCommentsAreAllowed(t *testing.T) {
	source := `// Package a documents the package.
package a

// Kind names a kind of thing.
type Kind int

const (
	// KindOne is the first kind.
	KindOne Kind = iota
)

// Config carries settings.
type Config struct {
	// Name is shown to the user.
	Name string
}

// Reader reads things.
type Reader interface {
	// Read reads one thing.
	Read() error
}

// Version is the current version.
var Version = "1"

// Run does the work.
func Run() {}
`
	findings, err := ScanFS(fstest.MapFS{"a.go": &fstest.MapFile{Data: []byte(source)}})
	if err != nil {
		t.Fatalf("ScanFS: %v", err)
	}
	if len(findings) != 0 {
		t.Fatalf("documentation comments must be allowed, got %v", findings)
	}
}

func TestCommentsInsideCodeAreRejected(t *testing.T) {
	source := `package a

// Run does the work.
func Run() int {
	// this explains a line
	value := 1
	return value // and this trails one
}

// a free floating comment

func Other() {}
`
	findings, err := ScanFS(fstest.MapFS{"a.go": &fstest.MapFile{Data: []byte(source)}})
	if err != nil {
		t.Fatalf("ScanFS: %v", err)
	}
	if len(findings) != 3 {
		t.Fatalf("got %d findings, want 3: %v", len(findings), findings)
	}
	for _, finding := range findings {
		if strings.Contains(finding.Text, "Run does the work") {
			t.Error("the documentation comment must not be reported")
		}
	}
}
